#############################################################################
# Config for ASkyGid
##############################################################################

island:
   distance: 10000

   protectionRange: 100

   # PVP is allowed or not.
   allowPvP: false
   allowNetherPvP: false
   # Allow players to throw enderpearls and teleport
   allowenderpearls: false
   # Allow fire spread 
   allowfirespread: false
   # Allow chests to be blown up by creepers or TNT
   allowchestdamage: false

# General Settings
general:
   # Check for updates - this will tell Ops and the console if there is a new
   # version available. It contacts dev.bukkit.org to request the latest version
   # info. It does not download the latest version or change any files
   checkupdates: true

   # Grid height - in multiples of 16
   islandlevel: 128

   # Name of the world - if it does not exist then it will be generated
   worldName: ASkyGrid

   # Use the control panel as the default display for /island
   # /island will always create an island if one does not exist
   # If the control panel is not used, then /island will teleport the player home
   usecontrolpanel: false

   # Create Nether - if this is false, the nether world will not be made and access to
   createnether: true


   # Commands to execute when a player starts a new island for the first time - NOT a reset
   startcommands:
   #- some other command
   
   # Removing mobs - this kills all monsters in the vicinity. Benefit is that it helps
   # players return to their island if the island has been overrun by monsters
   # Con is that it kills any mob grinders 
   # Remove mobs when logging in
   loginremovemobs: true

   # Remove mobs when /island.
   islandremovemobs: false
   
   # Mob white list - these mobs will NOT be removed when logging in or doing /island
   # Options are: Blaze, Cave_Spider, Creeper, Enderman, Endermite, Giant, Guardian,
   # Pig_Zombie, Silverfish, Skeleton, Spider, Witch, Wither, Zombie
   mobwhitelist:
   - Wither
   - Enderman
   - Pig_Zombie

   # Sets the limit for number of monsters that can spawn in a chunk in this world. 
   # Note: this does not limit the number of monsters, just how many spawn naturally.
   # Note: If set to a negative number the world will use the server-wide spawn limit instead.
   # Max is 100
   monsterspawnlimit: 70
   
   # Sets the limit for number of animals that can spawn in a chunk in this world. 
   # Note: If set to a negative number the world will use the server-wide spawn limit instead.
   # Max is 100
   animalspawnlimit: 15
   
   # Sets the limit for number of water animals [squid] that can spawn in a chunk in this world. 
   # Note: If set to a negative number the world will use the server-wide spawn limit instead.
   # Max is 100
   wateranimalspawnlimit: 15

   ##### Economy ######
   # Use economy or not. If true, an economy plugin is required. If false,
   # no money is used or give and the mini-shop is disabled.
   # If there is no economy plugin present anyway, money will be automatically
   # disabled.
   useeconomy: true

   # Reset Money - if this is true, will reset the player's money to
   # the starting money (see below) when they start an island or reset
   # Recommendation is that this is set to true, but if you run multi-worlds
   # make sure your economy handles multi-worlds too.
   resetmoney: false

   # Starting money - this is how much money new players will have as their
   # balance at the start of an island. 
   startingmoney: 10.00

   # Reset Challenges - if this is true, player's challenges will reset when they
   # reset an island
   resetchallenges: true

   # Reset inventory - if true, the player's inventory will be cleared when they start
   # or restart and island. Default is true.
   # Note: if you have MultiInv running or a similar inventory control plugin, that
   # plugin may still reset the inventory when the world changes.
   resetinventory: true

   # Reset Ender Chest - if true, the player's Ender Chest will be cleared when they
   # start or restart their island. Default is false.
   # NOTE: Ender Chests span worlds, so it will clear ALL chests. In general,
   # Enderchests should not be allowed in ASkyblock unless you only run the ASkyblock
   # world. Ender Chest crafting and use is governed by the askyblock.craft.enderchest
   # permission.
   resetenderchest: false

   # Nether spawn protection radius - this is the distance around the nether spawn
   # that will be protected from player interaction (breaking blocks, pouring lava etc.)
   # Minimum is 0 (not recommended), maximum is 100. Default is 25.
   # Only applies to standard nether.
   netherspawnradius: 25

   # Broadcast 1st time challenge completion messages to all players.
   # Change to false if the spam becomes too much.
   broadcastmessages: true

   # Allow /island teleport when falling. If set to false, all teleporting is
   # disabled until death from the void or until you hit something.
   # See commands that this will block too
   allowfallingteleport: true
   blockingcommands:
   - home
   #- anotherCommand
   #- andAnotherOne

   # Remove non-repeatable challenges from the challenge GUI when complete
   removecompleteonetimechallenges: false

   # Add enchanted glow to completed challenges (does not work with all clients)
   # Also currently adds an "enchanted" line of text...
   addcompletedglow: true

   # Default maximum number of homes a player can have. Min = 1
   # Accessed via sethome <number> or go <number>
   # Use this permission to set for specific user groups: askyblock.island.maxhomes.<number>  
   maxhomes: 1

   # Have player's respawn on their island if they die
   respawnonisland: false

   # Warp panel - GUI for welcome warp signs. If set to false, old-style
   # text will be used
   usewarppanel: true
   
   # Mute death messages
   mutedeathmessages: false
   
   # Config.yml version. DO NOT EDIT. This number only changes if the latest
   # plugin config has been updated. If a new config is detected, it will be
   # auto-saved to config.new.yml.
   version: ${version}
