#############################################################################
# Config for ASkyGid
##############################################################################

general:   
   # Grid height - max is 256
   gridheight: 128
   
   # Spawn height - height where players will spawn. Can be less than the grid height
   spawnheight: 128

   # Name of the world - if it does not exist then it will be generated
   worldName: ASkyGrid
   # Create a Grid Nether - if this is false, the nether grid world will not be made
   createnether: true

   # distance around 0,0 where players can spawn
   # Example, 1000 will randomly spawn players between -1000,-1000 to 1000, 1000
   distance: 1000

   # Protection radius given when planting a Welcome Sign
   # Players can control what happens within their protected space
   # Value of 20 means a 21x21 square at all heights with the warp block in the center
   # If a player removes their sign, the protection is dropped.
   # Players can trust other players with their space
   protectionRange: 20

   ### Settings for the whole world
   ### Players cannot customize these settings
   # Allow lava or water flow into or out of a district
   allowflowin: true
   allowflowout: true
   # Allow chests to be blown up by creepers or TNT
   allowchestdamage: true
   # Allow TNT damage
   allowTNTdamage: true
   #[true/false] PVP is allowed or denied.
   allowPvP: true
   # Allow players to throw enderpearls and teleport
   allowenderpearls: true
   
   ### Default in-claim settings. Owners will be able to customize the settings
   ### using the control panel
   # Other players can break blocks or not or generally damage things
   allowbreakblocks: false
   # Other players can place blocks
   allowplaceblocks: false
   # Allow players to be able to sleep in beds not on their island
   allowbeduse: false
   # Allow players to use buckets, either fill or dump them
   allowbucketuse: false
   # Allow players to shear sheep
   allowshearing: false
   # Allow players to use doors or trapdoors. If a door is operated by a button or redstone, this does not count
   allowdooruse: false
   # Allow players to use levers or buttons
   allowleverbuttonuse: false
   # Allow players to trample crops
   allowcroptrample: false
   # Allow players to access chests of any kind, droppers, dispensers and hoppers
   allowchestaccess: false
   # Allow players to access furnaces
   allowfurnaceuse: false
   # Allow players to adjust diodes or comparators
   allowredstone: false
   # Allow players to use jukeboxes, eject discs and hit note blocks
   allowmusic: false
   # Allow players to use crafting benches
   allowcrafting: true
   # Allow players to use cauldrons and brewing stands
   allowbrewing: false
   # Allow gates to be used
   allowgateuse: false
   # Allow non-monster mobs to be hurt
   allowhurtmobs: false
   
   # Commands to execute when a player starts for the first time
   # Commands will be run as console. Use [player] to substitute the player's name
   startcommands:
   - give [player] bread 1
   
   # Remove mobs - this kills all monsters in the vicinity when the player logs in. 
   loginremovemobs: false

   # Remove mobs when /asg.
   gridremovemobs: false
   
   # Mob white list - these mobs will NOT be removed when logging in or doing /asg
   # Options are: Blaze, Cave_Spider, Creeper, Enderman, Endermite, Giant, Guardian,
   # Pig_Zombie, Silverfish, Skeleton, Spider, Witch, Wither, Zombie
   mobwhitelist:
   - Wither
   - Enderman
   - Pig_Zombie

   # Sets the limit for number of monsters that can spawn in a chunk in this world. 
   # Note: this does not limit the number of monsters, just how many spawn naturally.
   # Note: If set to a negative number the world will use the server-wide spawn limit instead.
   # Max is 100
   monsterspawnlimit: 70
   
   # Sets the limit for number of animals that can spawn in a chunk in this world. 
   # Note: If set to a negative number the world will use the server-wide spawn limit instead.
   # Max is 100
   animalspawnlimit: 15
   
   # Sets the limit for number of water animals [squid] that can spawn in a chunk in this world. 
   # Note: If set to a negative number the world will use the server-wide spawn limit instead.
   # Max is 100
   wateranimalspawnlimit: 15

   ##### Economy ######
   # Use economy or not. If true, an economy plugin is required. If false,
   # no money is used or give and the mini-shop is disabled.
   # If there is no economy plugin present anyway, money will be automatically
   # disabled.
   useeconomy: true

   # Reset Money - if this is true, will reset the player's money to
   # the starting money (see below) when they start.
   # Recommendation is that this is set to true, but if you run multi-worlds
   # make sure your economy handles multi-worlds too.
   resetmoney: false

   # Starting money - this is how much money new players will have as their
   # balance at the start. 
   startingmoney: 10.00

   # Reset Ender Chest - if true, the player's Ender Chest will be cleared when they
   # start or restart their island. Default is false.
   # NOTE: Ender Chests span worlds, so it will clear ALL chests. In general,
   # Enderchests should not be allowed in ASkyblock unless you only run the ASkyblock
   # world. Ender Chest crafting and use is governed by the askyblock.craft.enderchest
   # permission.
   resetenderchest: false

   # Nether spawn protection radius - this is the distance around the nether spawn
   # that will be protected from player interaction (breaking blocks, pouring lava etc.)
   # Minimum is 0 (not recommended), maximum is 100. Default is 25.
   # Only applies to standard nether.
   netherspawnradius: 25

   # Broadcast 1st time challenge completion messages to all players.
   # Change to false if the spam becomes too much.
   broadcastmessages: true

   # Allow /island teleport when falling. If set to false, all teleporting is
   # disabled until death from the void or until you hit something.
   # See commands that this will block too
   allowfallingteleport: true
   blockingcommands:
   - home
   #- anotherCommand
   #- andAnotherOne

   # Remove non-repeatable challenges from the challenge GUI when complete
   removecompleteonetimechallenges: false

   # Add enchanted glow to completed challenges (does not work with all clients)
   # Also currently adds an "enchanted" line of text...
   addcompletedglow: true

   # Default maximum number of homes a player can have. Min = 1
   # Accessed via sethome <number> or go <number>
   # Use this permission to set for specific user groups: askyblock.island.maxhomes.<number>  
   maxhomes: 1

   # Have player's respawn on their island if they die
   respawnonisland: true

   # Warp panel - GUI for welcome warp signs. If set to false, old-style
   # text will be used
   usewarppanel: true
   
   # Mute death messages
   mutedeathmessages: false
   
   # Config.yml version. DO NOT EDIT. This number only changes if the latest
   # plugin config has been updated. If a new config is detected, it will be
   # auto-saved to config.new.yml.
   version: ${version}
