name: ASkyGrid
main: com.wasteofplastic.askygrid.ASkyGrid
version: ${version}
api-version: legacy
description: A SkyGrid Plugin
author: tastybento
depend: [Vault]
softdepend: [WorldGuard]
load: startup
loadbefore: [Multiverse-Core]
commands:
    asg:
        description: Main player command
        aliases: [asky]
        usage:  |
             /asg help
    asgadmin:
        description: Admin commands
        usage:  |
            /asgadmin
    asgc:
        description: Game challenges
        aliases: [c, challenge, challenges]
        usage:  |  
            /asgc
permissions:    
  askygrid.*:
    children:
      askygrid.player.*:
        children:
          askygrid.player.create:
            description: Let the player use the /skygrid command
            default: true
          askygrid.player.sethome:
            description: Let the player set their skygrid teleport point
            default: true
          askygrid.player.challenges:
            description: Let the player use the /challenges command
            default: true
          askygrid.player.warp:
            description: Let the player use /skygrid warp to warp to a players skygrid
            default: true
          askygrid.player.addwarp:
            description: Let the player place a Welcome warp sign
            default: true
      askygrid.mod.*:
        children:
          askygrid.mod.bannedcommands:
            decription: Let a moderator use banned commands
            default: false
          askygrid.mod.info:
            description: Let a moderator see info on a player
            default: op
          askygrid.mod.challenges:
            description: Let a moderator access challenge commands 
            default: op
          askygrid.mod.sethome:
            description: Allows setting of a player's home position
            default: op
          askygrid.mod.tp:
            description: Allows teleport to a player's home position
            default: op
      askygrid.admin.*:
        children:
          askygrid.admin.reload:
            description: Reload the config.yml
            default: op